global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'application'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:5000']
